// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:companion/src/hive/hive_adapters.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(CompanyModelAdapter());
    registerAdapter(CompanyToContactModelAdapter());
    registerAdapter(ContactModelAdapter());
    registerAdapter(PimModelAdapter());
    registerAdapter(SettingsModelAdapter());
  }
}
