name: companion
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  auto_route: ^9.2.2

  hooks_riverpod:
  riverpod_annotation:
  flutter_hooks:
  path_provider: ^2.1.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  velocity_x: ^4.2.1
  google_nav_bar: ^5.0.7
  flutter_screenutil: ^5.9.3
  google_fonts: ^6.2.1
  cuid2: ^3.1.0
  url_launcher: ^6.3.1
  multi_dropdown: ^3.0.1
  accordion: ^2.6.0
  disclosure: ^2.2.0
  json_hive_generator: ^1.0.2
  file_picker: ^8.1.7
  permission_handler: ^11.3.1
  shared_preferences: ^2.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.14
  auto_route_generator:
  custom_lint:
  riverpod_generator: ^2.6.3
  riverpod_lint: ^2.6.3
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
