name: companion
description: "A new Flutter project."
publish_to: "none"
version: 0.1.2

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  auto_route: ^9.2.2

  riverpod_annotation:
  path_provider: ^2.1.5
  velocity_x: ^4.2.1
  google_nav_bar: ^5.0.7
  flutter_screenutil: ^5.9.3
  cuid2: ^3.1.0
  url_launcher: ^6.3.1
  file_picker: ^8.1.7
  permission_handler: ^11.3.1
  flutter_riverpod: ^2.6.1
  form_builder_validators: ^11.1.1
  confirm_dialog: ^1.0.4
  faker: ^2.2.0
  sqflite: ^2.4.1
  path: ^1.9.0
  drift: ^2.23.1
  drift_flutter: ^0.2.4
  shared_preferences: ^2.3.5
  drift_db_viewer: ^2.1.0
  animate_do: ^3.3.4
  hugeicons: ^0.0.7
  share_plus: ^10.1.4
  animated_list_plus: ^0.5.2
  talker_riverpod_logger: ^4.6.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.14
  auto_route_generator:
  custom_lint:
  riverpod_generator: ^2.6.3
  riverpod_lint: ^2.6.3
  freezed: ^2.5.7
  drift_dev: ^2.23.1

flutter:
  uses-material-design: true
