name: companion
description: "A new Flutter project."
publish_to: "none"
version: 0.1.1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  auto_route: ^9.2.2

  riverpod_annotation:
  path_provider: ^2.1.5
  velocity_x: ^4.2.1
  google_nav_bar: ^5.0.7
  flutter_screenutil: ^5.9.3
  cuid2: ^3.1.0
  url_launcher: ^6.3.1
  disclosure: ^2.2.0
  file_picker: ^8.1.7
  permission_handler: ^11.3.1
  hive_ce: ^2.8.0+3
  hive_ce_flutter: ^2.2.0
  flutter_riverpod: ^2.6.1
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  flutter_form_builder: ^9.7.0
  form_builder_validators: ^11.1.1
  confirm_dialog: ^1.0.4
  faker: ^2.2.0
  sqflite: ^2.4.1
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.14
  auto_route_generator:
  custom_lint:
  riverpod_generator: ^2.6.3
  riverpod_lint: ^2.6.3
  hive_ce_generator: ^1.8.1
  freezed: ^2.5.7
  json_serializable: ^6.9.0

flutter:
  uses-material-design: true
